version: '2.0'

services:


  # сервер, где запущено приложение
  message-scheduler-prod:
    image: rgru/message-scheduler:latest
    container_name: message-scheduler
    restart: always
    ports:
      - 8088:8088

