version: '2.0'

services:


  # сервер, где запущено приложение
  message-scheduler-prod:
    image: message-scheduler-prod
    container_name: message-scheduler-prod
    restart: always
    ports:
      - 5500:5500
    volumes: 
      - ./../uploaded-files:/app/uploads

